name: check

on:
  push:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.42.4

      - run: deno test
